package notifications;

@:cppInclude("notifications/Notification_defines.h") @:include("notifications/Notification_defines.h")
@:native("NotificationModuleStatus")
extern enum NotificationModuleStatus {
	@:native("NOTIFICATION_MODULE_RESULT_SUCCESS")
	NOTIFICATION_MODULE_RESULT_SUCCESS;

	@:native("NOTIFICATION_MODULE_RESULT_MODULE_NOT_FOUND")
	NOTIFICATION_MODULE_RESULT_MODULE_NOT_FOUND;

	@:native("NOTIFICATION_MODULE_RESULT_MODULE_MISSING_EXPORT")
	NOTIFICATION_MODULE_RESULT_MODULE_MISSING_EXPORT;

	@:native("NOTIFICATION_MODULE_RESULT_MODULE_INVALID_EXPORT")
	NOTIFICATION_MODULE_RESULT_MODULE_INVALID_EXPORT;

	@:native("NOTIFICATION_MODULE_RESULT_UNSUPPORTED_VERSION")
	NOTIFICATION_MODULE_RESULT_UNSUPPORTED_VERSION;

	@:native("NOTIFICATION_MODULE_RESULT_INVALID_ARGUMENT")
	NOTIFICATION_MODULE_RESULT_INVALID_ARGUMENT;

	@:native("NOTIFICATION_MODULE_RESULT_LIB_UNINITIALIZED")
	NOTIFICATION_MODULE_RESULT_LIB_UNINITIALIZED;

	@:native("NOTIFICATION_MODULE_RESULT_UNSUPPORTED_COMMAND")
	NOTIFICATION_MODULE_RESULT_UNSUPPORTED_COMMAND;

	@:native("NOTIFICATION_MODULE_RESULT_OVERLAY_NOT_READY")
	NOTIFICATION_MODULE_RESULT_OVERLAY_NOT_READY;

	@:native("NOTIFICATION_MODULE_RESULT_UNSUPPORTED_TYPE")
	NOTIFICATION_MODULE_RESULT_UNSUPPORTED_TYPE;

	@:native("NOTIFICATION_MODULE_RESULT_ALLOCATION_FAILED")
	NOTIFICATION_MODULE_RESULT_ALLOCATION_FAILED;

	@:native("NOTIFICATION_MODULE_RESULT_INVALID_HANDLE")
	NOTIFICATION_MODULE_RESULT_INVALID_HANDLE;

	@:native("NOTIFICATION_MODULE_RESULT_UNKNOWN_ERROR")
	NOTIFICATION_MODULE_RESULT_UNKNOWN_ERROR;
}

@:native("NotificationModuleAPIVersion")
extern class NotificationModuleAPIVersion {}

@:native("NotificationModuleHandle")
extern class NotificationModuleHandle {}

@:native("NotificationModuleNotificationFinishedCallback")
typedef NotificationModuleNotificationFinishedCallback = Void;

@:native("_NMColor")
extern typedef NMColor = {
    @:native("r")
    var r:Float;

    @:native("g")
    var g:Float;

    @:native("b")
    var b:Float;

    @:native("a")
    var a:Float;
}

@:native("NotificationModuleNotificationType")
extern enum NotificationModuleNotificationType {
	@:native("NOTIFICATION_MODULE_NOTIFICATION_TYPE_INFO")
	NOTIFICATION_MODULE_NOTIFICATION_TYPE_INFO;

	@:native("NOTIFICATION_MODULE_NOTIFICATION_TYPE_ERROR")
	NOTIFICATION_MODULE_NOTIFICATION_TYPE_ERROR;

	@:native("NOTIFICATION_MODULE_NOTIFICATION_TYPE_DYNAMIC")
	NOTIFICATION_MODULE_NOTIFICATION_TYPE_DYNAMIC;
}

@:native("NotificationModuleStatusFinish")
extern enum NotificationModuleStatusFinish {
	@:native("NOTIFICATION_MODULE_STATUS_FINISH")
	NOTIFICATION_MODULE_STATUS_FINISH;

	@:native("NOTIFICATION_MODULE_STATUS_FINISH_WITH_SHAKE")
	NOTIFICATION_MODULE_STATUS_FINISH_WITH_SHAKE;
}

@:native("NotificationModuleNotificationOption")
extern enum NotificationModuleNotificationOption {
	@:native("NOTIFICATION_MODULE_DEFAULT_OPTION_BACKGROUND_COLOR")
	NOTIFICATION_MODULE_DEFAULT_OPTION_BACKGROUND_COLOR;

	@:native("NOTIFICATION_MODULE_DEFAULT_OPTION_TEXT_COLOR")
	NOTIFICATION_MODULE_DEFAULT_OPTION_TEXT_COLOR;

	@:native("NOTIFICATION_MODULE_DEFAULT_OPTION_DURATION_BEFORE_FADE_OUT")
	NOTIFICATION_MODULE_DEFAULT_OPTION_DURATION_BEFORE_FADE_OUT;

	@:native("NOTIFICATION_MODULE_DEFAULT_OPTION_FINISH_FUNCTION")
	NOTIFICATION_MODULE_DEFAULT_OPTION_FINISH_FUNCTION;

	@:native("NOTIFICATION_MODULE_DEFAULT_OPTION_FINISH_FUNCTION_CONTEXT")
	NOTIFICATION_MODULE_DEFAULT_OPTION_FINISH_FUNCTION_CONTEXT;

	@:native("NOTIFICATION_MODULE_DEFAULT_OPTION_KEEP_UNTIL_SHOWN")
	NOTIFICATION_MODULE_DEFAULT_OPTION_KEEP_UNTIL_SHOWN;
}
